movie_info = read.csv("tmdb_5000_movies.csv", header = TRUE)
credits_info = read.csv("tmdb_5000_credits.csv", header = TRUE)
install.packages("dplyr")
library(dplyr)

english_movies = dplyr::filter(movie_info, original_language  == "en")
not_english_movies = dplyr::filter(movie_info, original_language  != "en")
not_avatar = dplyr::filter(movie_info, title != "Avatar")
high_budget = dplyr::filter(movie_info, budget > 100000000)
low_budget = dplyr::filter(movie_info, budget <= 100000000)
avg_high_budget = mean(high_budget$budget)
avg_low_budget = mean(low_budget$budget)
movie_info$year = substr(movie_info$release_date, 7, 11)
movie_info$month = substr(movie_info$release_date, 4, 5)
grouped_movie = dplyr::group_by(movie_info, year)
avg_year_budget = dplyr::summarize(grouped_movie, total_budget = mean(budget))
grouped_movie_month = dplyr::group_by(movie_info, month)
avg_month_revenue = dplyr::summarize(grouped_movie_month, avg_revenue = mean(revenue))
movie_2016 = dplyr::filter(movie_info, year == 2016)
inner_joined_data = dplyr::inner_join(movie_2016, credits_info, by = "id")
left_join = dplyr::left_join(movie_2016, credits_info, by = "id")
actor_100million = dplyr::filter(left_join, budget>100000000)
